server:
  port: 8080
spring:
  application:
    name: "Reportes"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
aws:
  region: "us-east-1"
  dynamodb:
#    endpoint: "http://localhost:8000"
    AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
    AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
entrypoint:
  sqs:
    region: "us-east-1"
#    endpoint: "http://localhost:4566"
    queueUrl: "${SQS_LISTENER_APROBADA:https://sqs.us-east-1.amazonaws.com/821368348315/SolicitudAprobadaQueue}"
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 10
    numberOfThreads: 1
    AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
    AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
