server:
  port: "${SERVER_PORT:8084}"
spring:
  application:
    name: "${SPRING_APP_NAME:Reportes}"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
aws:
  region: "${AWS_REGION:us-east-1}"
  dynamodb:
    AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
    AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
entrypoint:
  sqs:
    region: "${AWS_REGION:us-east-1}"
#    endpoint: "http://localhost:4566"
    queueUrl: "${SQS_LISTENER_APROBADA:https://sqs.us-east-1.amazonaws.com/821368348315/SolicitudAprobadaQueue}"
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 10
    numberOfThreads: 1
    AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
    AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "${CORS_ALLOWED_ORIGINS:http://localhost:4200,http://localhost:8084}"
security:
  jwt:
    secret: "${SPRING_SECURITY_JWT_SECRET:0Dz2RFrDttxXG9ZgQ9s6nJ8lcnFv9HQ1mFtuG3B0TXQ=}"
    expiration-ms: "${SPRING_SECURITY_JWT_EXPIRATION_MS:3600000}"
adapter:
  sqs:
    region: "${AWS_REGION:us-east-1}"
    queueUrl: "${SQS_INFORME_DIARIO:https://sqs.us-east-1.amazonaws.com/821368348315/ReporteDiarioQueue}"
#    endpoint: "http://localhost:4566 # For localstack only"
